name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        nuget-api-key: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build LiqPaySDK/LiqPay.SDK.sln --configuration Release
    - name: Pack
      run: dotnet pack LiqPaySDK/LiqPay.SDK.sln --configuration Release
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/jtone123/index.json -Username jtone123 -Password ${{secrets.GITHUB_TOKEN}}
    - name: Publish Nuget
      run: dotnet nuget push "bin/Release/liqpay-dotnet.1.0.0.nupkg" --source "github"
